version: '3.8'
services:
  postgres:
    image: postgres
    container_name: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - redis:/data

volumes:
  postgres:
    name: vehicle-data-volume
  redis:
    name: redis-cache
